security:
    encoders:
        OCWm\OCWBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        user_db:
            entity: { class: OCWm\OCWBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/app/login$
            security: false

        buscar:
            pattern: ^/app/buscar$
            security: false

        secured_area:
            pattern:    ^/app
            form_login:
                check_path: /app/login_check
                login_path: /app/login
                default_target_path: /app
                always_use_default_target_path: true
            logout:
                path:   /app/logout
                target: /

    access_control:
        - { path: ^/app, roles: [ROLE_ADMIN, ROLE_USER] }
