<?php

namespace OCWm\OCWBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * comentariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class comentariosRepository extends EntityRepository
{
}