<?php

namespace OCWm\OCWBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * posts_hilo_discusionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class posts_hilo_discusionRepository extends EntityRepository
{
}