<?php

namespace OCWm\OCWBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * roles_ocwRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class roles_ocwRepository extends EntityRepository
{
}