<?php

namespace OCWm\OCWBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tipos_preguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipos_preguntaRepository extends EntityRepository
{
}